import './globals.css';
import ThemeProvider from '@/components/ThemeProvider';
import Footer from '@/components/layout/Footer/Footer';
import Header from '@/components/layout/Header/Header';
import Hero from '@/components/layout/Hero/Hero';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = [
    { href: '/about', label: 'Sobre' },
    // { href: '/galery', label: 'Galeria' },
    { href: '/facities', label: 'Serviços' },
    { href: '/rooms', label: 'Quartos' },
    { href: '/contact', label: 'Contato' },
  ];
  return (
    <html lang="pt-br">
      <body>
        <ThemeProvider>
          <Header theme="dark" links={links} />
          <Hero
            title="Lorem Ipsum"
            subtitle="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            backgroundImage="https://picsum.photos/1920"
          ></Hero>
          {children}
          <Footer></Footer>
        </ThemeProvider>

      </body>
    </html>
  );
}
